# Generated by Django 3.2 on 2022-02-23 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='created_by',
            new_name='created_at',
        ),
    ]
