# Generated by Django 3.2 on 2022-02-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_created_by_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='excerpt',
            field=models.TextField(),
        ),
    ]
