# Generated by Django 4.0.2 on 2022-02-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_posts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.CharField(choices=[('News', 'news'), ('Business', 'business'), ('Health', 'health'), ('Tech', 'tech'), ('Law', 'law')], max_length=20),
        ),
    ]
