# Generated by Django 4.0.2 on 2022-03-14 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_posts_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_categories', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='excerpt',
        ),
        migrations.AddField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='status',
            field=models.CharField(choices=[('Draft', 'draft'), ('Published', 'published')], default='Published', max_length=20),
        ),
        migrations.AlterField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.categories'),
        ),
    ]
