# Generated by Django 4.0.2 on 2022-03-15 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_categories_category_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category_img',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_img1',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='posts',
            name='post_img2',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
