# Generated by Django 4.0.2 on 2022-03-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_rename_post_img1_posts_post_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category_img',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
