# Generated by Django 4.0.2 on 2022-03-23 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_post_options_alter_categories_category_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='category_img',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_img',
        ),
    ]
